name: compilepaper
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      DIR: .
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends texlive pandoc texlive-bibtex-extra texlive-fonts-recommended texlive-xetex lmodern biber latexmk python3 python3-yaml xz-utils make gpg-agent
      - name: Configure LaTeX environment
        working-directory: ${{ env.DIR }}
        run: |
          mkdir -p "${HOME}/texmf"
          tlmgr init-usertree
          tlmgr option repository https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/2021/tlnet-final/
          tlmgr install academicons
      - name: pandoc compile
        working-directory: ${{ env.DIR }}
        run: make all
      - name: move
        run: mkdir -p github_artifacts && mv ${{ env.DIR }}/*.pdf ./github_artifacts/
      - name: Upload pdf as artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDF files
          path: ./github_artifacts
  deploy:
    needs: [paper]
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'CaptainSifff/paper_teaching-learning-RSE' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
